### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by gaahrdner** [slack-samples/deno-triage-rotation#22]
Hello, I'm unable to deploy the latest version of this app; I was able to successfully run it locally however.

```
~/code/RotationManager via ⬢ v16.20.0 via 🦕 v1.35.0 using ☁️  REDACTED took 56.5s
➜ slack deploy
? Choose a deployed environment REDACTED

📚 App Manifest
   Updated app manifest for "RotationManager" in REDACTED

🏠 Workspace Install
   Installed "RotationManager" app to REDACTED
   Updated app icon: assets/icon.png
   Finished in 2.9s

⚡ Listing triggers installed to the app...

🔗 Shortcut trigger:

   Manage rotation REDACTED (shortcut)
   Created: 2023-07-21 12:04:56 -05:00 (13 minutes ago)
   Collaborators:
     REDACTED
   Can be found and used by:
     everyone
   https://slack.com/shortcuts/REDACTED


⠹ Packaging app for deploymenterror: npm specifiers have not yet been implemented for this subcommand (https://github.com/denoland/deno/issues/15960). Found: npm:@slack/types@2.8.0
Error bundling function file: open_form
error: Uncaught Error: Error bundling function file: open_form
throw new Error(`Error bundling function file: ${fnId}`);
            ^
at createFunctionFile (https://deno.land/x/deno_slack_hooks@1.1.0/build.ts:82:13)
at eventLoopTick (ext:core/01_core.js:183:11)
at async validateAndCreateFunctions (https://deno.land/x/deno_slack_hooks@1.1.0/build.ts:39:5)
at async https://deno.land/x/deno_slack_hooks@1.1.0/build.ts:127:3
Check /Users/gaahrdner/.slack/logs/slack-debug-20230721.log for full error logs

⠸ Packaging app for deployment🚫 Deploy error: error packaging project: Command for 'BuildProject' returned an error: exit status 1 (sdk_hook_invocation_failed)

Suggestion:

Run `slack doctor` to check that your system dependencies are up-to-date.

⠸ Packaging app for deployment%
```

Here are the results from `slack doctor`:

```
➜ slack doctor

SYSTEM

    ✔ Operating System (the kernel and drivers)
        Version: darwin (amd64)

    ✔ Deno (a JavaScript runtime)
        Version: v1.35.0
        Recommendation: We suggest using the latest version of Deno

    ✔ Git (a version control system)
        Version: git version 2.41.0


SLACK

    ✔ CLI (this tool for building Slack apps)
        Version: 2.5.1

    ✔ Configurations (any adjustments to settings)
        System ID: REDACTED
        Last updated: 2023-07-21 11:49:39 -05:00
        Experiments: None

    ✔ Credentials (your Slack authentication)
        Team domain: REDACTED
        Team ID: REDACTED
        User ID: REDACTED
        Last updated: 2023-07-21 11:49:56 -05:00
        Authorization level: Workspace
        Token status: Valid


PROJECT

    ✔ Configurations (your project's CLI settings)
        Project ID: REDACTED

    ✔ Dependencies (requisites for development)
        deno_slack_hooks: 1.1.0
        deno_slack_sdk: 2.1.4
        deno_slack_api: 2.1.1

Errors: 0

💌 We would love to know how things are going
   Survey your development experience with slack feedback
   ```

**Comment by srajiang** [comment]
Hey @gaahrdner - Yep I can reproduce this. Looks like [a change made to this sample](https://github.com/slack-samples/deno-triage-rotation/pull/19) recently is the cause of the issue. 

While we investigate potentially reverting this change, to get unblocked for now, I'd suggest updating the two files `manifest.ts` and `functions/open_form/blocks.ts` to use the skypack cd for imports. That works for me

**Comment by gaahrdner** [comment]
Thanks very much for the quick response @srajiang; reverting that commit made it successfully deploy.  My Slack admin also appreciates it since he won't get bombarded by any more installation requests 🤣

**Comment by gaahrdner** [comment]
@srajiang I just realized no one else can use this application (i.e. they can't even see the slash command) after it's been deployed; is there something else that I should be doing? I noticed I can add others as Collaborators via the CLI and then reinstall the app but...that's not really scalable. Do you have any suggestions? 

Happy to open a different issue as well if that's helpful.

**Comment by misscoded** [comment]
Hi @gaahrdner! Sorry for our dropping the ball on a timely reply here. I do hope you came upon the answer in the meantime, but as for making functions available for use by others, we recommend checking out the [function distribution documentation](https://api.slack.com/automation/deploy#slack-deploy__function-distribution) and using the `distribute` command. 

Let us know if that solves the issue you've raised!

**Comment by gaahrdner** [comment]
Hi @misscoded , thanks for that, this seems to have worked!
